eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA__SERVER_ADDRESS:http://localhost:8761/eureka}
management:
  tracing:
    sampling:
      probability: 1.0
